# See https://github.com/lowlighter/metrics for documentation
# This workflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Readme Metrics
on:
  schedule: [{ cron: "* 0 * * 0" }] # Updates every week on Sunday
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base:
          base_skip: yes
          plugin_achievements: yes
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_display: compact # Use compact display
